### ISSUE TITLE
How to use? What is the exmple meaning?

### ISSUE THREAD

**Issue by Hodoio** [trinhthinh388/fetch-interceptors#13]
I hope a example to use 'axios-fetch-interceptors'

**Comment by trinhthinh388** [comment]
Hi!
This library has the same approach with `axios`.
We can use it like this:
```javascript
window.fetch.interceptors.request.use((request) => {
 // Handling request
})
```

I will update the docs soon!!

**Comment by trinhthinh388** [comment]
The docs is updated
Thanks for your feedback
